### ISSUE TITLE
Add to unity

### ISSUE THREAD

**Issue by WongResearch** [eamonwoortman/RestSharp.Unity#2]
Great fork. Would you mind giving a brief introduction how to import this to a unity project?

Cheers,

**Comment by eamonwoortman** [comment]
Hey Nick,

Thanks for your interest in this fork.
I've been meaning to get to you earlier, but got caught on some 'end-of-the-year' todo lists. 

Basically, you just build the RestSharp.NET35.Unity project from the solution and place the output DLL's in the `/Plugins` folder of your Unity project.

I've created a repository with a RestSharp.Unity test project, you can find it at https://github.com/eamonwoortman/RestSharp.Unity.Tester, I hope this can be to use to you.

Let me know if you can get it to work.

**Comment by WongResearch** [comment]
Thank you Eamon -  much appreciated.
