### ISSUE TITLE
Crash with iOS access denied exception when using IL2CPP scripting backend

### ISSUE THREAD

**Issue by Deepscorn** [eamonwoortman/RestSharp.Unity#4]
RestSharp keeps crashing with:

Access to the path "/private/var/mobile/Containers/Data/Application/[numbers here]/.config" is denied

Stack: https://www.dropbox.com/s/x1luj0tloc5c7hg/imgpsh_fullsize.png?dl=0

And corresponding string in mono library (don't know if it will help):
https://github.com/mono/mono/blob/master/mcs/class/Mono.Security/Mono.Security.X509/X509Store.cs#L287

RestSharp is built from here, latest version:
https://github.com/eamonwoortman/RestSharp.Unity/tree/master/RestSharp/RestSharp.Net35.csproj

Unity 5.3.1f1

We were using this RestSharp in Unity for ages and there were no problems on Android, IOs and Unity Player.

The only problem that was on both Windows and Android forced us to disable certificate checking that way:

``` c
#if (UNITY_ANDROID || UNITY_EDITOR)
            // workaround for "Unable to find /System/Library/Frameworks/Security.framework/Security" and "Error getting response stream (Write: The authentication or decryption has failed.): SendFailure"
            // http://answers.unity3d.com/questions/521069/android-unable-to-find-systemlibraryframeworkssecu.html
            // platforms: Android, Windows 10
            ServicePointManager.ServerCertificateValidationCallback = (p1, p2, p3, p4) => true;
#endif
```

But that fix doesn't work for ios. Looks like mono uses another way (<a href="https://developer.xamarin.com/api/type/Mono.Security.Protocol.Tls.CertificateValidationCallback2/">CertificateValidationCallback2</a>) to validate certificate and crashes while trying to create directory :)

**Comment by eamonwoortman** [comment]
Hi Deepscorn,

Thanks for reporting this issue in such detail.
I have re-opened the initial SSL issue(#1) which I needed to refacor anyway.

I will take a look at `CertificateValidationCallback2` to see if we can use it in the same manner as `CertificateValidationCallback`.

**Comment by Deepscorn** [comment]
Thank you for an answer! I really appreciate your work!

**Comment by eamonwoortman** [comment]
Just out of curiousity, have you already tried to hook the `CertificateValidationCallback2`callback and return true? Also, did the crash occur wth all https endpoints or just specific cases(eg. self-signed certificates)?

**Comment by Deepscorn** [comment]
I wanted to do so. But I don't know where to set that. Exception stack contains only mono code... I would be glad if you share how to do it. No, I didn't tested for different https endpoints. PS It may be only ios >=8 related error because of the path

**Comment by eamonwoortman** [comment]
Unfortunatly I have not been able to reproduce the crash with some private endpoints(and the public httpbin one). Could you share your endpoint URL so I can reproduce the error? Or, in case it has to remain private, could you provide me with a public https URL which causes the same exception?

Also  `CertificateValidationCallback2` is only available as of Mono version 4.0.0, Unity is somewhere around Mono 2.0. I think we need to find the solution somewhere else.

**Comment by Deepscorn** [comment]
You are right. It was an xcode configuration problem. My coworker didn't update xcode project configuration which is really a big mistake. 
PS We update configuration files manually (not just use configuration files generated by Unity) because we have regular ios app implemented in same app too which needs it's own configuration entries.
After updating xcode project configuration files problem left away. Forgive me for your time, I will delve into every detail next time, before making an issue.
Closing this. Thanks for your great work! Latest version works very fast and stable!

**Comment by eamonwoortman** [comment]
Good to see the issue has resolved itself :) 

Hint: perhaps you want to automate those post build steps with post-processors like XUPorter(https://github.com/onevcat/XUPorter) or build servers like Teamcity/ Jenkins.

I will still refactor some of the SSL validation code in the next week, but nothing which will break the compatibility(see #1 ).

**Comment by Deepscorn** [comment]
Thank you!
